import type { Event, Person } from "./types";

export const people: Person[] = [
  {
    slug: "mustafa-matar",
    name: { ar: "مصطفى مطر", en: "Mustafa Matar" },
    country: { ar: "فلسطين", en: "Palestine" },
    city: { ar: "غزة", en: "Gaza" },
    role: { ar: "شاعر وكاتب", en: "Poet and writer" },
    initials: { ar: "م.م", en: "MM" },
    visible: true,
    shortBio: {
      ar: "شاعر فلسطيني شارك في عدد من الأمسيات والملتقيات الثقافية.",
      en: "A Palestinian poet who has taken part in cultural evenings and literary forums.",
    },
    fullBio: {
      ar: "يهتم بتجارب الشعر العربي المعاصر وبناء الجسور الثقافية بين الشعراء والجمهور. شارك في مهرجانات وملتقيات داخل المنطقة العربية وخارجها، وأسهم في فعاليات تجمع بين الإلقاء والحوار الأدبي.",
      en: "His work explores contemporary Arabic poetry and cultural exchange between poets and audiences. He has participated in festivals and forums across the Arab region and abroad.",
    },
    website: "https://example.org",
    works: [
      { title: { ar: "على حافة الضوء", en: "At the Edge of Light" }, type: { ar: "ديوان", en: "Poetry collection" }, year: 2024 },
      { title: { ar: "ذاكرة المدن", en: "Memory of Cities" }, type: { ar: "قصيدة", en: "Poem" } },
      { title: { ar: "أمسية إسطنبول", en: "Istanbul Recital" }, type: { ar: "فيديو إلقاء", en: "Recitation video" }, externalUrl: "https://youtube.com" },
    ],
    eventSlugs: ["istanbul-poetry-forum-2026", "arab-poetry-festival-eighth"],
  },
  {
    slug: "ibtisam-al-samadi",
    name: { ar: "ابتسام الصمادي", en: "Ibtisam Al-Samadi" },
    country: { ar: "سوريا", en: "Syria" },
    role: { ar: "شاعرة", en: "Poet" },
    initials: { ar: "ا.ص", en: "IS" },
    visible: true,
    shortBio: { ar: "شاعرة سورية مشاركة في فعاليات عربية ودولية.", en: "A Syrian poet active in Arab and international events." },
    fullBio: { ar: "تكتب القصيدة العربية الحديثة وتشارك في أمسيات ومهرجانات أدبية متعددة.", en: "She writes contemporary Arabic poetry and participates in literary festivals and readings." },
    works: [],
    eventSlugs: ["istanbul-poetry-forum-2026", "arab-poetry-festival-eighth"],
  },
  {
    slug: "hassan-talab",
    name: { ar: "حسن طلب", en: "Hassan Talab" },
    country: { ar: "مصر", en: "Egypt" },
    role: { ar: "شاعر", en: "Poet" },
    initials: { ar: "ح.ط", en: "HT" },
    visible: true,
    shortBio: { ar: "شاعر مصري وضيف في عدد من البرامج الثقافية.", en: "An Egyptian poet and guest at several cultural programs." },
    fullBio: { ar: "له حضور في المشهد الشعري العربي ومشاركات في أمسيات وندوات ثقافية.", en: "He is active in the Arab poetry scene and has joined readings and seminars." },
    works: [],
    eventSlugs: ["contemporary-arabic-poetry-evening"],
  },
  {
    slug: "khaled-al-yasari",
    name: { ar: "خالد اليساري", en: "Khaled Al-Yasari" },
    country: { ar: "العراق", en: "Iraq" },
    role: { ar: "إعلامي ومقدم", en: "Media presenter" },
    initials: { ar: "خ.ي", en: "KY" },
    visible: true,
    shortBio: { ar: "مقدم فعاليات وإعلامي ثقافي.", en: "A cultural presenter and media professional." },
    fullBio: { ar: "يسهم في تقديم وإدارة الحوارات والفعاليات الثقافية والشعرية.", en: "He presents and moderates literary and cultural events." },
    works: [],
    eventSlugs: ["istanbul-poetry-forum-2026", "arab-poetry-festival-eighth"],
  },
  {
    slug: "sumaya-wadi",
    name: { ar: "سمية وادي", en: "Sumaya Wadi" },
    country: { ar: "الجزائر", en: "Algeria" },
    role: { ar: "شاعرة", en: "Poet" },
    initials: { ar: "س.و", en: "SW" },
    visible: true,
    shortBio: { ar: "شاعرة جزائرية مشاركة في الملتقيات العربية.", en: "An Algerian poet participating in Arab literary forums." },
    fullBio: { ar: "لها مشاركات في أمسيات شعرية وبرامج تعنى بالتبادل الثقافي العربي.", en: "She participates in poetry readings and Arab cultural exchange programs." },
    works: [],
    eventSlugs: ["young-poets-bridges"],
  },
];

export const events: Event[] = [
  {
    slug: "istanbul-poetry-forum-2026",
    status: "upcoming",
    title: { ar: "ملتقى القصيدة العربية في إسطنبول — الدورة الأولى", en: "Arabic Poem Forum in Istanbul — First Edition" },
    type: { ar: "ملتقى", en: "Forum" },
    shortDescription: { ar: "ملتقى ثقافي دولي يجمع نخبة من الشعراء العرب ضمن برنامج من الأمسيات واللقاءات.", en: "An international cultural forum bringing Arab poets together for readings and conversations." },
    fullDescription: { ar: "تنظم الجمعية الدولية للشعراء العرب هذا الملتقى بوصفه مساحة للتفاعل الثقافي والتعريف بالتجارب الشعرية العربية. يجمع البرنامج بين القراءات الشعرية والحوارات الأدبية وفقرات التكريم.", en: "The association organizes this forum as a space for cultural exchange and the presentation of Arab poetic experiences, combining readings, conversations, and recognition ceremonies." },
    startDate: "2026-08-05T15:00:00+03:00",
    endDate: "2026-08-10T18:00:00+03:00",
    timezone: "Europe/Istanbul",
    country: { ar: "تركيا", en: "Türkiye" },
    city: { ar: "إسطنبول", en: "Istanbul" },
    venue: { ar: "قاعة ثقافية في إسطنبول", en: "A cultural venue in Istanbul" },
    attendance: "requestApproval",
    image: "/images/istanbul-event.png",
    featured: true,
    participantSlugs: ["mustafa-matar", "ibtisam-al-samadi", "khaled-al-yasari"],
    program: [
      { time: "15:00", duration: "5", title: { ar: "الافتتاح", en: "Opening" }, description: { ar: "الترحيب بالمشاركين والجمهور.", en: "Welcome to participants and guests." } },
      { time: "15:05", duration: "90", title: { ar: "الأمسية الشعرية", en: "Poetry reading" }, description: { ar: "قراءات شعرية بمشاركة شعراء من عدة دول.", en: "Poetry readings by participants from several countries." } },
      { time: "16:50", duration: "30", title: { ar: "أقلام واعدة", en: "Emerging Voices" }, description: { ar: "تقديم تجارب أدبية وشعرية جديدة.", en: "Introducing new literary voices." } },
      { time: "17:20", duration: "10", title: { ar: "التكريم والختام", en: "Recognition and closing" }, description: { ar: "تكريم المشاركين واختتام البرنامج.", en: "Recognition of participants and closing remarks." } },
    ],
    gallery: ["/images/association-photo.png", "/images/istanbul-event.png", "/images/poets-poster.png"],
  },
  {
    slug: "contemporary-arabic-poetry-evening",
    status: "upcoming",
    title: { ar: "أمسية الشعر العربي المعاصر", en: "Contemporary Arabic Poetry Evening" },
    type: { ar: "أمسية شعرية", en: "Poetry evening" },
    shortDescription: { ar: "قراءات شعرية وحوار مفتوح حول تحولات القصيدة العربية.", en: "Poetry readings and an open discussion on contemporary Arabic poetry." },
    fullDescription: { ar: "أمسية تجمع شعراء وقراء في لقاء يركز على التجارب المعاصرة ومسارات القصيدة الحديثة.", en: "An evening for poets and readers focusing on contemporary experiences and modern poetic forms." },
    startDate: "2026-09-22T18:00:00+03:00",
    timezone: "Africa/Cairo",
    country: { ar: "مصر", en: "Egypt" },
    city: { ar: "القاهرة", en: "Cairo" },
    attendance: "open",
    image: "/images/event-square.png",
    participantSlugs: ["hassan-talab"],
    program: [],
    gallery: ["/images/event-square.png"],
  },
  {
    slug: "young-poets-bridges",
    status: "upcoming",
    title: { ar: "جسور القصيدة: لقاء الشعراء الشباب", en: "Poetry Bridges: Young Poets Gathering" },
    type: { ar: "برنامج ثقافي", en: "Cultural program" },
    shortDescription: { ar: "منصة ثقافية لعرض تجارب جديدة وبناء روابط بين الأجيال.", en: "A cultural platform for new voices and intergenerational exchange." },
    fullDescription: { ar: "برنامج يتيح للشعراء الشباب تقديم تجاربهم والتفاعل مع ضيوف من المشهد الأدبي.", en: "A program enabling young poets to present their work and engage with established literary guests." },
    startDate: "2026-11-12T16:00:00+03:00",
    timezone: "Asia/Amman",
    country: { ar: "الأردن", en: "Jordan" },
    city: { ar: "عمّان", en: "Amman" },
    attendance: "invitation",
    image: "/images/poets-poster.png",
    participantSlugs: ["sumaya-wadi"],
    program: [],
    gallery: ["/images/poets-poster.png"],
  },
  {
    slug: "arab-poetry-festival-eighth",
    status: "past",
    title: { ar: "مهرجان الشعر العربي — الدورة الثامنة", en: "Arab Poetry Festival — Eighth Edition" },
    type: { ar: "مهرجان", en: "Festival" },
    shortDescription: { ar: "أرشيف الدورة الثامنة وصورها وبرنامجها الختامي.", en: "Archive of the eighth edition, including its program and gallery." },
    fullDescription: { ar: "وثّقت الدورة الثامنة مشاركة شعراء من دول متعددة ضمن أمسيات وندوات وفقرات تكريم.", en: "The eighth edition brought poets from multiple countries together for readings, seminars, and recognition ceremonies." },
    startDate: "2026-06-27T15:00:00+03:00",
    endDate: "2026-06-29T17:00:00+03:00",
    timezone: "Europe/Istanbul",
    country: { ar: "تركيا", en: "Türkiye" },
    city: { ar: "إسطنبول", en: "Istanbul" },
    attendance: "invitation",
    image: "/images/poets-poster.png",
    participantSlugs: ["mustafa-matar", "ibtisam-al-samadi", "khaled-al-yasari"],
    program: [],
    gallery: ["/images/poets-poster.png", "/images/association-photo.png"],
  },
];
