import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { DemoForm } from "@/components/forms/DemoForm";
import { Icon } from "@/components/ui/Icon";
import { PageHero } from "@/components/ui/PageHero";
import { isLocale } from "@/i18n/config";
import { getEventBySlug } from "@/lib/content";
import { localize } from "@/lib/content/types";
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; return { title: locale === "ar" ? "طلب المشاركة" : "Participation request" }; }
export default async function ParticipatePage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<{ event?: string }> }) { const { locale: raw } = await params; if (!isLocale(raw)) notFound(); const { event } = await searchParams; const selected = event ? await getEventBySlug(event, raw) : null; return <main><PageHero eyebrow={raw === "ar" ? "انضم إلى برامجنا" : "Join our programs"} title={raw === "ar" ? "طلب المشاركة" : "Participation request"} description={raw === "ar" ? "أرسل طلبًا أوليًا واضحًا، وسيقوم فريق الجمعية بمراجعته والتواصل معك خارج الموقع." : "Send a clear initial request. The association team will review it and follow up outside the website."} /><section className="section"><div className="container form-layout"><DemoForm locale={raw} type="participation" requestedEvent={selected ? { slug: selected.slug, title: localize(selected.title, raw) } : undefined} /><aside className="sidebar-card card process-card"><h2>{raw === "ar" ? "ما الذي يحدث بعد الإرسال؟" : "What happens next?"}</h2><ol><li><span><Icon name="email" /></span><div><strong>{raw === "ar" ? "استلام الطلب" : "Request received"}</strong><p>{raw === "ar" ? "يحفظ الطلب مباشرة داخل صندوق الوارد في لوحة الإدارة." : "The request is saved directly in the admin inbox."}</p></div></li><li><span><Icon name="people" /></span><div><strong>{raw === "ar" ? "مراجعة البيانات" : "Team review"}</strong><p>{raw === "ar" ? "تراجع الإدارة البيانات ونوع المشاركة والفعالية المطلوبة." : "The team reviews your details, role, and selected event."}</p></div></li><li><span><Icon name="whatsapp" /></span><div><strong>{raw === "ar" ? "التواصل" : "Follow-up"}</strong><p>{raw === "ar" ? "يتم التواصل عبر البريد أو WhatsApp عند توفر فرصة مناسبة." : "Follow-up happens by email or WhatsApp when an opportunity is available."}</p></div></li></ol></aside></div></section></main>; }
