import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { DemoForm } from "@/components/forms/DemoForm";
import { Icon } from "@/components/ui/Icon";
import { PageHero } from "@/components/ui/PageHero";
import { isLocale } from "@/i18n/config";
import { getSiteSettings } from "@/lib/content";
const whatsappURL = (number?: string) => number ? `https://wa.me/${number.replace(/\D/g, "")}` : undefined;
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; return { title: locale === "ar" ? "تواصل معنا" : "Contact" }; }
export default async function ContactPage({ params }: { params: Promise<{ locale: string }> }) { const { locale: raw } = await params; if (!isLocale(raw)) notFound(); const settings = await getSiteSettings(raw); const whatsapp = whatsappURL(settings?.whatsapp); return <main><PageHero eyebrow={raw === "ar" ? "نحن قريبون" : "Stay connected"} title={raw === "ar" ? "تواصل معنا" : "Contact us"} description={raw === "ar" ? "أرسل رسالتك من خلال النموذج، أو استخدم قنوات التواصل الرسمية المنشورة." : "Send a message through the form or use the published official channels."} /><section className="section"><div className="container form-layout"><DemoForm locale={raw} type="contact" /><aside className="contact-stack">{settings?.officialEmail ? <div className="sidebar-card card contact-card"><Icon name="email" /><div><h3>{raw === "ar" ? "البريد الرسمي" : "Official email"}</h3><a className="arrow-link" href={`mailto:${settings.officialEmail}`}>{settings.officialEmail}</a></div></div> : null}{whatsapp ? <div className="sidebar-card card contact-card"><Icon name="whatsapp" /><div><h3>WhatsApp</h3><a className="arrow-link" href={whatsapp} target="_blank" rel="noopener noreferrer">{settings?.whatsapp}</a></div></div> : null}{settings?.socialLinks.map((link) => <div className="sidebar-card card contact-card" key={link.url}><Icon name="globe" /><div><h3>{link.platform}</h3><a className="arrow-link" href={link.url} target="_blank" rel="noopener noreferrer">{raw === "ar" ? "فتح الصفحة" : "Open page"}</a></div></div>)}{!settings?.officialEmail && !whatsapp ? <div className="sidebar-card card"><h3>{raw === "ar" ? "بيانات التواصل" : "Contact details"}</h3><p>{raw === "ar" ? "أضف البريد ورقم WhatsApp من إعدادات الموقع داخل لوحة الإدارة." : "Add the official email and WhatsApp number from Site Settings in the admin panel."}</p></div> : null}</aside></div></section></main>; }
