/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'event-types': EventType;
    'event-series': EventSery;
    countries: Country;
    cities: City;
    events: Event;
    people: Person;
    'literary-works': LiteraryWork;
    partners: Partner;
    'participation-requests': ParticipationRequest;
    'contact-messages': ContactMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'event-types': EventTypesSelect<false> | EventTypesSelect<true>;
    'event-series': EventSeriesSelect<false> | EventSeriesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'literary-works': LiteraryWorksSelect<false> | LiteraryWorksSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'participation-requests': ParticipationRequestsSelect<false> | ParticipationRequestsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    'editorial-overview': EditorialOverviewWidget;
    collections: CollectionsWidget;
  };
  strictDraftTypes: true;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  internalSeedKey?: string | null;
  /**
   * Briefly describe the image for accessibility and search engines.
   */
  alt: string;
  caption?: string | null;
  credit?: string | null;
  sourceEvent?: (number | null) | Event;
  cloudinaryPublicId?: string | null;
  cloudinarySecureUrl?: string | null;
  cloudinaryAssetId?: string | null;
  cloudinaryVersion?: number | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Generated automatically when empty and editable before publishing.
   */
  slug: string;
  /**
   * Click to pick an existing item from the list before adding a new one. Use the + button only if it doesn't already exist.
   */
  eventType: number | EventType;
  /**
   * Click to pick an existing item from the list before adding a new one. Use the + button only if it doesn't already exist.
   */
  series?: (number | null) | EventSery;
  editionName?: string | null;
  editionNumber?: number | null;
  shortDescription: string;
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredOnHomepage?: boolean | null;
  startDateTime: string;
  endDateTime?: string | null;
  timezone:
    | 'Asia/Gaza'
    | 'Asia/Hebron'
    | 'Europe/Istanbul'
    | 'Asia/Amman'
    | 'Africa/Cairo'
    | 'Asia/Riyadh'
    | 'Asia/Dubai'
    | 'UTC';
  /**
   * Click to pick an existing item from the list before adding a new one. Use the + button only if it doesn't already exist.
   */
  country: number | Country;
  /**
   * Pick the country first — only its cities are then listed. Click to choose from the list before using + to add a new city.
   */
  city?: (number | null) | City;
  venueName?: string | null;
  addressText?: string | null;
  attendanceMode: 'open' | 'invitation' | 'requestApproval';
  attendanceNote?: string | null;
  coverImage?: (number | null) | Media;
  socialImage?: (number | null) | Media;
  posterImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  youtubeUrl?: string | null;
  participants?:
    | {
        person: number | Person;
        eventRole: 'poet' | 'presenter' | 'guest' | 'judge' | 'honoree' | 'organizer' | 'other';
        customRoleLabel?: string | null;
        isFeatured?: boolean | null;
        /**
         * Sets the display order in lists — smaller numbers appear first. Leave it 0 if order doesn't matter.
         */
        order: number;
        id?: string | null;
      }[]
    | null;
  programMode: 'single' | 'perDay' | 'sharedAcrossDays';
  programDays?:
    | {
        label: string;
        date?: string | null;
        items: {
          title: string;
          startTime?: string | null;
          durationMinutes?: number | null;
          presenter?: (number | null) | Person;
          participants?: (number | Person)[] | null;
          description?: string | null;
          venue?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  honorees?: (number | Person)[] | null;
  closingReport?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  recommendations?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedEvents?: (number | Event)[] | null;
  archive: {
    sourceFacebookUrl?: string | null;
    verificationStatus: 'unverified' | 'needsReview' | 'verified' | 'approvedWithGaps';
    verificationNotes?: string | null;
    verifiedBy?: (number | null) | User;
    verifiedAt?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    customOgImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * تُستخدم أنواع الفعاليات في الفلاتر ومفتاح ألوان الروزنامة / Event types power calendar filters and colors.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types".
 */
export interface EventType {
  id: number;
  name: string;
  /**
   * Generated automatically when empty and editable before publishing.
   */
  slug: string;
  /**
   * When enabled, this item is visible to visitors and in pickers. Uncheck to hide it without deleting it.
   */
  isActive: boolean;
  /**
   * Sets the display order in lists — smaller numbers appear first. Leave it 0 if order doesn't matter.
   */
  order?: number | null;
  /**
   * لون النقطة والوسم داخل الروزنامة. مثال: #B88A2C / Dot and badge color in the calendar.
   */
  calendarColor?: string | null;
  showInCalendarLegend?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-series".
 */
export interface EventSery {
  id: number;
  name: string;
  /**
   * Generated automatically when empty and editable before publishing.
   */
  slug: string;
  description?: string | null;
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Browse the list first to confirm the country doesn't already exist before adding a new one — this avoids duplicates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  /**
   * Generated automatically when empty and editable before publishing.
   */
  slug: string;
  /**
   * When enabled, this item is visible to visitors and in pickers. Uncheck to hide it without deleting it.
   */
  isActive: boolean;
  /**
   * Sets the display order in lists — smaller numbers appear first. Leave it 0 if order doesn't matter.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Browse the list first to confirm the city doesn't already exist before adding a new one — this avoids duplicates.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * Generated automatically when empty and editable before publishing.
   */
  slug: string;
  /**
   * Click to pick an existing item from the list before adding a new one. Use the + button only if it doesn't already exist.
   */
  country: number | Country;
  /**
   * When enabled, this item is visible to visitors and in pickers. Uncheck to hide it without deleting it.
   */
  isActive: boolean;
  /**
   * Sets the display order in lists — smaller numbers appear first. Leave it 0 if order doesn't matter.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  /**
   * Generated automatically when empty and editable before publishing.
   */
  slug: string;
  country: number | Country;
  city?: (number | null) | City;
  penName?: string | null;
  profileImage?: (number | null) | Media;
  roles?:
    | (
        | 'poet'
        | 'writer'
        | 'critic'
        | 'artist'
        | 'media'
        | 'presenter'
        | 'guest'
        | 'boardMember'
        | 'teamMember'
        | 'judge'
        | 'honoree'
      )[]
    | null;
  shortBio?: string | null;
  fullBio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  profession?: string | null;
  website?: string | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'x' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  phone?: string | null;
  showContactPublicly?: boolean | null;
  showInPublicDirectory: boolean;
  displayOrder?: number | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    customOgImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "literary-works".
 */
export interface LiteraryWork {
  id: number;
  title: string;
  /**
   * Generated automatically when empty and editable before publishing.
   */
  slug: string;
  person: number | Person;
  type: 'poetryCollection' | 'book' | 'poem' | 'article' | 'audio' | 'recitationVideo' | 'interview' | 'other';
  coverImage?: (number | null) | Media;
  publicationYear?: number | null;
  publisher?: string | null;
  description?: string | null;
  externalUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * Generated automatically when empty and editable before publishing.
   */
  slug: string;
  logo?: (number | null) | Media;
  website?: string | null;
  description?: string | null;
  relationshipType: 'partner' | 'sponsor' | 'organizer' | 'supporter' | 'media';
  associationWide: boolean;
  events?: (number | Event)[] | null;
  isActive: boolean;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participation-requests".
 */
export interface ParticipationRequest {
  id: number;
  fullName: string;
  country: string;
  city?: string | null;
  email: string;
  whatsapp: string;
  shortBio?: string | null;
  participationType: 'poet' | 'writer' | 'artist' | 'media' | 'other';
  requestedEvent?: (number | null) | Event;
  externalUrl?: string | null;
  message?: string | null;
  consent: boolean;
  status: 'new' | 'reviewed' | 'contacted' | 'closed' | 'spam';
  internalNotes?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phoneOrWhatsapp?: string | null;
  subject?: string | null;
  message: string;
  consent: boolean;
  status: 'new' | 'read' | 'contacted' | 'closed' | 'spam';
  internalNotes?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'event-types';
        value: number | EventType;
      } | null)
    | ({
        relationTo: 'event-series';
        value: number | EventSery;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'literary-works';
        value: number | LiteraryWork;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'participation-requests';
        value: number | ParticipationRequest;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  internalSeedKey?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  sourceEvent?: T;
  cloudinaryPublicId?: T;
  cloudinarySecureUrl?: T;
  cloudinaryAssetId?: T;
  cloudinaryVersion?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types_select".
 */
export interface EventTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  order?: T;
  calendarColor?: T;
  showInCalendarLegend?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-series_select".
 */
export interface EventSeriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eventType?: T;
  series?: T;
  editionName?: T;
  editionNumber?: T;
  shortDescription?: T;
  fullDescription?: T;
  featuredOnHomepage?: T;
  startDateTime?: T;
  endDateTime?: T;
  timezone?: T;
  country?: T;
  city?: T;
  venueName?: T;
  addressText?: T;
  attendanceMode?: T;
  attendanceNote?: T;
  coverImage?: T;
  socialImage?: T;
  posterImage?: T;
  gallery?: T;
  youtubeUrl?: T;
  participants?:
    | T
    | {
        person?: T;
        eventRole?: T;
        customRoleLabel?: T;
        isFeatured?: T;
        order?: T;
        id?: T;
      };
  programMode?: T;
  programDays?:
    | T
    | {
        label?: T;
        date?: T;
        items?:
          | T
          | {
              title?: T;
              startTime?: T;
              durationMinutes?: T;
              presenter?: T;
              participants?: T;
              description?: T;
              venue?: T;
              image?: T;
              id?: T;
            };
        id?: T;
      };
  honorees?: T;
  closingReport?: T;
  recommendations?: T;
  relatedEvents?: T;
  archive?:
    | T
    | {
        sourceFacebookUrl?: T;
        verificationStatus?: T;
        verificationNotes?: T;
        verifiedBy?: T;
        verifiedAt?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        customOgImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  city?: T;
  penName?: T;
  profileImage?: T;
  roles?: T;
  shortBio?: T;
  fullBio?: T;
  profession?: T;
  website?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  email?: T;
  phone?: T;
  showContactPublicly?: T;
  showInPublicDirectory?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        customOgImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "literary-works_select".
 */
export interface LiteraryWorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  person?: T;
  type?: T;
  coverImage?: T;
  publicationYear?: T;
  publisher?: T;
  description?: T;
  externalUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  description?: T;
  relationshipType?: T;
  associationWide?: T;
  events?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participation-requests_select".
 */
export interface ParticipationRequestsSelect<T extends boolean = true> {
  fullName?: T;
  country?: T;
  city?: T;
  email?: T;
  whatsapp?: T;
  shortBio?: T;
  participationType?: T;
  requestedEvent?: T;
  externalUrl?: T;
  message?: T;
  consent?: T;
  status?: T;
  internalNotes?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phoneOrWhatsapp?: T;
  subject?: T;
  message?: T;
  consent?: T;
  status?: T;
  internalNotes?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  associationName: string;
  slogan?: string | null;
  logo?: (number | null) | Media;
  defaultSocialImage?: (number | null) | Media;
  officialEmail: string;
  whatsapp: string;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'x' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroMode: 'automatic' | 'featuredEvent' | 'institutional';
  featuredEvent?: (number | null) | Event;
  institutionalHero?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  featuredPeople?: (number | Person)[] | null;
  selectedPartners?: (number | Partner)[] | null;
  /**
   * اختر الأشخاص الذين يظهرون في قسم إدارة الجمعية / Select the people shown in the association team section.
   */
  associationTeam?: (number | Person)[] | null;
  /**
   * اتركها فارغة ليحسب الموقع الإحصاءات من المحتوى المنشور / Leave empty to calculate statistics from published content.
   */
  statistics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * محجوز لمرحلة الأخبار المستقبلية / Reserved for a future news module.
   */
  showNews?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  associationName?: T;
  slogan?: T;
  logo?: T;
  defaultSocialImage?: T;
  officialEmail?: T;
  whatsapp?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroMode?: T;
  featuredEvent?: T;
  institutionalHero?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  featuredPeople?: T;
  selectedPartners?: T;
  associationTeam?: T;
  statistics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  showNews?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial-overview_widget".
 */
export interface EditorialOverviewWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}